services:
  jobspring_ddb:
    image: mysql:8.0.41
    container_name: jobspring_ddb
    environment:
      MYSQL_ROOT_PASSWORD: user-root
      MYSQL_DATABASE: jobspringdb
      MYSQL_USER: account_user
      MYSQL_PASSWORD: account_pass
    ports:
      - "3320:3306"
    volumes:
      - jobspringdb_data:/var/lib/mysql
    networks:
      - network

  jobspring_dredis:
    image: redis:8.0.0
    container_name: jobspring_dredis
    volumes:
      - jobspringredis_data:/data
    ports:
      - "6390:6379"
    networks:
      - network

volumes:
  jobspringdb_data:
  jobspringredis_data:

networks:
  network: